development:
  adapter: mysql2
  encoding: utf8
  database: jokes_development
  username: root
  password: 
  host: localhost
  socket: /var/run/mysqld/mysqld.sock


test:
  adapter: mysql2
  encoding: utf8
  database: jokes_test
  username: root
  password: 
  host: localhost
  socket: /var/run/mysqld/mysqld.sock



production:
  adapter: mysql2
  encoding: utf8
  database: jokes_production
  username: root
  password:
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
